In [1]:
# Step1. NumPyをインポート
import numpy as np

# Step2. 行列AとBを定義
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# Step3. 行列の積を計算
C = np.dot(A, B)

# Step4. 計算結果を表示
print("行列の積：")
print(C)

# Step5. 最大値を求めて表示
max_value = np.max(C)
print("最大値：", max_value)


行列の積：
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値： 47
